services:
  lb:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./etc/nginx.conf:/etc/nginx/nginx.conf

  registry:
    build: ./RegistryService
    depends_on:
      - db      
  
  content:
    build: ./ContentService
    depends_on:
      - db
      - registry

  question:
    build: ./QuestionService
    depends_on:
      - db
      - registry
      - content
  
  progress:
    build: ./ProgressService
    depends_on:
      - db
      - registry
      - content
      - question
  
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: journey
      POSTGRES_PASSWORD: J0urn3yDoenc@Db
      POSTGRES_DB: journey
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: